### ISSUE TITLE
Proper styles for input text

### ISSUE THREAD

**Issue by vrajroham** [matiastucci/vue-input-tag#34] opened 2017-09-04 13:52 UTC
Using latest version of component. Input component `(.new-tag)` is not styled properly. I'm importing this component in **Laravel 5.5** within another controller. Following is the output of component.

![screenshot from 2017-09-04 19 15 42](https://user-images.githubusercontent.com/12662173/30029135-920ca758-91a5-11e7-84d1-2bc6410b12b9.png)
-----

I tried overriding css of `new-tag` but no luck.

**Comment by ianaya89** [comment] 2018-01-03 13:45
@vrajroham I can't reproduce this issue. Is it possible that the component's styles are being affected by your project CSS?

**Comment by matiastucci** [comment] 2018-01-28 21:58
I'm closing this until having an answer

**Closed by matiastucci** 2018-01-28 21:58 UTC
Labels: question
